#ifndef __BODYINFO_HRP2HRP3_H__
#define __BODYINFO_HRP2HRP3_H__

#define RARM_JOINT0 R_SHOULDER_P
#define RARM_JOINT1 R_SHOULDER_R
#define RARM_JOINT2 R_SHOULDER_Y
#define RARM_JOINT3 R_ELBOW_P
#define RARM_JOINT4 R_WRIST_Y
#define RARM_JOINT5 R_WRIST_R
#define RARM_JOINT6 R_THUMBMP_P
#define LARM_JOINT0 L_SHOULDER_P
#define LARM_JOINT1 L_SHOULDER_R
#define LARM_JOINT2 L_SHOULDER_Y
#define LARM_JOINT3 L_ELBOW_P
#define LARM_JOINT4 L_WRIST_Y
#define LARM_JOINT5 L_WRIST_R
#define LARM_JOINT6 L_THUMBCM_P

#define RLEG_JOINT2 R_HIP_P
#define RLEG_JOINT3 R_KNEE_P
#define RLEG_JOINT4 R_ANKLE_P
#define LLEG_JOINT2 L_HIP_P
#define LLEG_JOINT3 L_KNEE_P
#define LLEG_JOINT4 L_ANKLE_P

#endif
